---
- hosts: [group1]
  become: true
  gather_facts: false
  vars_files:
    - vars/main.yml
  tasks:
          
          - name: Create workspace for archives user
            file:
               path: /archives/{{ user_to_delete }}
               state: directory
               mode: 0640

          - name: Create a tar.gz archive of a single file
            archive:
               path: /home/{{ user_to_delete }}/
               dest: /archives/{{ user_to_delete }}/{{ user_to_delete }}.gz
               format: gz
               force_archive: true 

          - name: Remove the old user
            user:
               name: "{{ user_to_delete }}"
               state: absent
               remove: yes

          - name: Remove the old group
            group:
               name: "{{ group_to_delete }}"
               state: absent
